#!/usr/bin/env node

const swarmgw = require('./index.js')()
const swarmhash = require('swarmhash')
const fs = require('fs')

var yargs = require('yargs')
  .usage('Usage: $0 [command]')
  .command('get <url>', 'Download content')
  .command('put <filename>', 'Upload file')
  .command('calculate <filename>', 'Calculate the hash only without uploading')
  .strict()
  .version()
  .showHelpOnFail(false, 'Specify --help for available options')
  .help()
  .demand(1, 'Must provide a command')

var argv = yargs.argv
var command = argv._[0]

function abort (msg) {
  console.log(msg || 'Error occured')
  process.exit(1)
}

switch (command) {
  case 'get':
    swarmgw.get(argv.url, function (err, ret) {
      if (err) {
        abort('Failed to download: ' + err)
      } else {
        console.log(ret)
      }
    })
    break
  case 'put':
    swarmgw.put(fs.readFileSync(argv.filename), function (err, ret) {
      if (err) {
        console.log('Failed to upload: ' + err)
      } else {
        console.log('Swarm hash: ' + ret)
      }
    })
    break
  case 'calculate':
    console.log('Swarm hash: ' + swarmhash(fs.readFileSync(argv.filename)).toString('hex'))
    break
}
